# Generated by Django 4.2.5 on 2023-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_skill_job_skills'),
        ('account', '0003_user_gender_user_interested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='job.skill'),
        ),
    ]
