# Generated by Django 4.2.5 on 2023-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
