# Generated by Django 4.2.5 on 2023-10-17 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='job_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
