# Generated by Django 4.2.5 on 2023-10-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
