# Generated by Django 4.2.5 on 2023-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
