# Generated by Django 4.2.5 on 2023-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
